---
development:
  cloud_name: CLOUD_NAME
  api_key: 'API_KEY'
  api_secret: SECRET_KEY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: CLOUD_NAME
  api_key: 'API_KEY'
  api_secret: SECRET_KEY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: CLOUD_NAME
  api_key: 'API_KEY'
  api_secret: SECRET_KEY
  enhance_image_tag: true
  static_image_support: false
